plugins {
    id 'java'
    id 'maven-publish'
}

group 'de.arthurpicht'
version '0.0.3-SNAPSHOT'
def artifact = 'ap-utils-logging'

repositories {
    maven { url "https://raw.githubusercontent.com/arthurpicht/mvn-repo/main/releases"}
    mavenCentral()
}

dependencies {
    implementation 'de.arthurpicht:ap-utils-core:1.22.0'
    implementation 'ch.qos.logback:logback-classic:1.5.2'

    testImplementation 'de.arthurpicht:ap-utils-io:0.0.24'

    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    withJavadocJar()
    withSourcesJar()
}

test {
    useJUnitPlatform()
}

base {
    archivesName = artifact
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = artifact
            from components.java
        }
    }
    repositories {
        maven {
            url = layout.buildDirectory.dir(project.gradle.gradleUserHomeDir.parent + "/gitrepos/ap/mvn-repo/releases")
        }
    }
}
